### ISSUE TITLE
Issue with Low of Day

### ISSUE THREAD

**Issue by ABDiscordBots** [markosole/yahoo-node-streamer#2]
`yaticker {
  id: 'MSFT',
  price: 246.89999389648438,
  time: Long { low: -1967757888, high: 377, unsigned: false },
  exchange: 'NMS',
  quoteType: 8,
  marketHours: 1,
  changePercent: 1.554787278175354,
  dayVolume: Long { low: 10287264, high: 0, unsigned: false },
  change: 3.779998779296875,
  priceHint: Long { low: 2, high: 0, unsigned: false } }`
  
  Issue with Low of day quote. Is there a protobuf file that has all the information contained in it?

**Comment by markosole** [comment]
Late reply on this, I do not think so, I will have to dig into Yahoo's API and check is there a source for that. I am not sure if that info is broadcasted in real time using ws. I'll check it. If you find anything you are welcome to share it
